---
apiVersion: v1
kind: Pod
metadata:
  name: laptop-pod
  labels:
    app: laptop-pod
spec:
  containers:
  - name: laptop
    image: <registry ip>:5000/laptop_docker
    imagePullPolicy: Always
    command: ["/bin/sleep", "3650d"]    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: laptop
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - pods/exec
  - secrets
  - serviceaccounts
  - nodes
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: laptop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: laptop
subjects:
- kind: ServiceAccount
  name: default
- kind: Group
  name: system:serviceaccounts:default
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: laptop
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: laptop
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: laptop


